@startuml ThingsBoardClient

class ThingsBoardClient {
  -client
  -twilight

  +connect()
  +disconnect()
  +send_gps(lat, lng, speed, course)
  +send_battery(pct)
  +send_temperature(temperature_c)
  +get_twilight(timeout_s)
  +attributes_callback(payload)
}

@enduml